config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :votes
  resources :ideas
  resources :events

  root to: "events#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :creator_id, numericality: { only_integer: true }
  validates :name, :when, presence: true

  has_many :ideas
  # def ideas
  #   Idea.where(event_id: self.id)
  # end


  has_many :votes, through: :ideas

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  # create validations for ideas, votes and events
  validates :event_id, :creator_id, numericality: { only_integer: true }
  validates :name, presence: true

  has_many :votes
  # def votes
  #   Vote.where(idea_id: self.id)
  # end

  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  validates :user_id, :idea_id, numericality: { only_integer: true }
  validates_uniqueness_of :user_id, scope: [ :idea_id ]

  belongs_to :idea
  # def idea
  #   Idea.find(self.idea_id)
  # end

  validate :users_can_only_vote_once_per_event
  def users_can_only_vote_once_per_event
    vote_count = self.idea.event.votes.where(user_id: self.user_id).count
    if vote_count > 0
      errors.add(:custom, "User has already voted for this event")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first
    devise_parameter_sanitizer.for(:sign_up) << :last
    devise_parameter_sanitizer.for(:sign_up) << :profile_pic

    devise_parameter_sanitizer.for(:account_update) << :first
    devise_parameter_sanitizer.for(:account_update) << :last
    devise_parameter_sanitizer.for(:account_update) << :profile_pic
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @idea = Idea.new
    @vote = Vote.new
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :when, :creator_id, :description)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    @idea.creator_id = current_user.id

    respond_to do |format|
      if @idea.save
        format.html { redirect_to :back, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
        format.js
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea_id = @idea.id
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:event_id, :creator_id, :name)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)
    @vote.user_id = current_user.id

    respond_to do |format|
      if @vote.save
        format.html { redirect_to :back, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
        format.js
      else
        # format.html { render :new }
        format.html { redirect_to :back, alert: 'There was an error creating your vote' }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:user_id, :idea_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/events/_event_idea.html.erb
<li id='idea_<%= idea.id %>' class="list-group-item idea-item">
  <!-- Single button -->
  <% if current_user.id == idea.creator_id %>
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        Your idea <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">

        <!-- make this destroy link remove the row through javascript -->
        <li><a data-remote="true" data-method="delete" href="<%= idea_url(idea) %>">Destroy</a></li>
        <li><a data-remote="true" href="<%= edit_idea_url(idea) %>">Edit</a></li>
      </ul>
    </div>
  <% end %>
  <span class="idea_text"><%= idea.name %></span>
  <% if event.votes.where(user_id: current_user.id).present? %>
    <% vote = Vote.where(user_id: current_user.id, idea_id: idea.id).first %>
    <% if vote %>
      <%= link_to(vote, {method: :delete, class: 'btn btn-danger btn-sm', remote: true}) do %>
        <i class="fa fa fa-times"></i>
      <% end %>
    <% end %>
  <% else %>
    <%= render 'events/event_vote', {vote: Vote.new, idea: idea} %>
  <% end %>
  <div class="pull-right">

  </div>
  <% if idea.votes.present? %>
    <span class="badge"><%= idea.votes.count %></span>
  <% end %>
</li>

app/views/events/_event_vote.html.erb
<%= form_for(vote, html: {class: 'button-submit'}, remote: true) do |f| -%>
  <%= f.hidden_field :idea_id, value: idea.id %>
  <button class="btn btn-default">
    <i class="fa fa-thumbs-o-up"></i>
  </button>
<% end %>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :when %>
    <%= f.input :creator_id %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/_idea_form.html.erb
<%= form_for(idea, html: {class: 'idea-form'}, remote: true) do |f| %>
  <%= f.text_field :name %>
  <input type="submit">
<% end %>

app/views/events/edit.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Event #<%= @event.id %></h3>
      </div>
      <div class="panel-body">
        <%= render 'form', event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="page-header">
  <h1>
    Events
    <%= link_to icon('plus'), new_event_path, class: "btn btn-lg btn-success" %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Events (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @events.each do |event| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Event #<%= event.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Name</dt>
          <dd><%= event.name %></dd>

          <dt>When</dt>
          <dd><%= event.when %></dd>

          <dt>Creator</dt>
          <dd><%= event.creator_id %></dd>

          <dt>Description</dt>
          <dd><%= event.description %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to icon('search-plus'), event, class: "btn btn-primary" %>

          <%= link_to icon('edit'), edit_event_url(event), class: "btn btn-warning" %>

          <%= link_to icon('trash-o'), event, method: :delete, data: { confirm: "Do you really want to delete this event?" }, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/events/new.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New Event</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Event #<%= @event.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Name</dt>
              <dd><%= @event.name %></dd>

              <dt>When</dt>
              <dd><%= @event.when %></dd>

              <dt>Creator</dt>
              <dd><%= @event.creator_id %></dd>

              <dt>Description</dt>
              <dd><%= @event.description %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to icon('chevron-left'), events_path, class: "btn btn-primary" %>

              <%= link_to icon('edit'), edit_event_path(@event), class: "btn btn-warning" %>

              <%= link_to icon('trash-o'), @event, method: :delete, data: { confirm: "Do you really want to delete this event?" }, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Add a new idea</h3>
      </div>
      <div class="panel-body">
        <%= form_for @idea, remote: true do |f| -%>
          <%= f.hidden_field :event_id, value: @event.id %>
          <%= f.text_field :name, class: 'form-control', placeholder: 'your idea...' %>
        <% end -%>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          Ideas
          <div class="pull-right">
            Vote count
          </div>
        </h3>
      </div>
      <ul class="list-group">
        <% @event.ideas.order(created_at: :desc).each do |idea| %>
          <%= render 'event_idea', {idea: idea, event: @event, vote: @vote} %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

app/views/ideas/_form.html.erb
<%= simple_form_for(@idea) do |f| %>
  <%= f.error_notification %>
  <ul>
  <div class="form-inputs">
    <%= f.input :event_id %>
    <%= f.input :creator_id %>
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ideas/create.js.erb
$('ul.list-group').prepend('<%= j(render('events/event_idea', {idea: @idea, event: @idea.event, vote: Vote.new })) %>');
$('#idea_name').val('');

app/views/ideas/destroy.js.erb
$('#idea_<%= @idea_id %>').fadeOut();

app/views/ideas/edit.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Idea #<%= @idea.id %></h3>
      </div>
      <div class="panel-body">
        <%= render 'form', idea: @idea %>
      </div>
    </div>
  </div>
</div>

app/views/ideas/edit.js.erb
$('#idea_<%= @idea.id %> .idea_text').replaceWith('<%= j(render 'events/idea_form', { idea: @idea }) %>')

app/views/ideas/index.html.erb
<div class="page-header">
  <h1>
    Ideas
    <%= link_to icon('plus'), new_idea_path, class: "btn btn-lg btn-success" %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Ideas (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @ideas.each do |idea| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Idea #<%= idea.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Event</dt>
          <dd><%= idea.event_id %></dd>

          <dt>Creator</dt>
          <dd><%= idea.creator_id %></dd>

          <dt>Name</dt>
          <dd><%= idea.name %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to icon('search-plus'), idea, class: "btn btn-primary" %>

          <%= link_to icon('edit'), edit_idea_url(idea), class: "btn btn-warning" %>

          <%= link_to icon('trash-o'), idea, method: :delete, data: { confirm: "Do you really want to delete this idea?" }, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/ideas/new.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New Idea</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', idea: @idea %>
      </div>
    </div>
  </div>
</div>

app/views/ideas/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Idea #<%= @idea.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Event</dt>
              <dd><%= @idea.event_id %></dd>

              <dt>Creator</dt>
              <dd><%= @idea.creator_id %></dd>

              <dt>Name</dt>
              <dd><%= @idea.name %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to icon('chevron-left'), ideas_path, class: "btn btn-primary" %>

              <%= link_to icon('edit'), edit_idea_path(@idea), class: "btn btn-warning" %>

              <%= link_to icon('trash-o'), @idea, method: :delete, data: { confirm: "Do you really want to delete this idea?" }, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

app/views/ideas/update.js.erb
$('#edit_idea_<%= @idea.id %>').replaceWith("<span class='idea_text'><%= @idea.name %></span>");

app/views/votes/_form.html.erb
<%= simple_form_for(@vote) do |f| %>
  <%= f.error_notification %>
  <% if @vote.errors.messages[:custom].present? %>
    <ul class="error_messages_container">
    <% @vote.errors.messages[:custom].each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :idea_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/votes/create.js.erb
$('#idea_<%= @vote.idea_id %>').replaceWith('<%= j(render 'events/event_idea', {idea: @vote.idea, event: @vote.idea.event, vote: Vote.new} ) %>');

<% @vote.idea.event.ideas.each do |idea| %>
  $('#idea_<%= idea.id %> #new_vote').hide()
<% end %>

app/views/votes/destroy.js.erb
<% @vote.idea.event.ideas.each do |idea| %>
  $('#idea_<%= idea.id %>').append("<%= j(render 'events/event_vote', {vote: Vote.new, idea: idea}) %>")
<% end %>

$('#idea_<%= @vote.idea_id %>').replaceWith('<%= j(render 'events/event_idea', {idea: @vote.idea, event: @vote.idea.event, vote: Vote.new} ) %>');

app/views/votes/edit.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Vote #<%= @vote.id %></h3>
      </div>
      <div class="panel-body">
        <%= render 'form', vote: @vote %>
      </div>
    </div>
  </div>
</div>

app/views/votes/index.html.erb
<div class="page-header">
  <h1>
    Votes
    <%= link_to icon('plus'), new_vote_path, class: "btn btn-lg btn-success" %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Votes (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @votes.each do |vote| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Vote #<%= vote.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>User</dt>
          <dd><%= vote.user_id %></dd>

          <dt>Idea</dt>
          <dd><%= vote.idea_id %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to icon('search-plus'), vote, class: "btn btn-primary" %>

          <%= link_to icon('edit'), edit_vote_url(vote), class: "btn btn-warning" %>

          <%= link_to icon('trash-o'), vote, method: :delete, data: { confirm: "Do you really want to delete this vote?" }, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/votes/new.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New Vote</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', vote: @vote %>
      </div>
    </div>
  </div>
</div>

app/views/votes/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Vote #<%= @vote.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>User</dt>
              <dd><%= @vote.user_id %></dd>

              <dt>Idea</dt>
              <dd><%= @vote.idea_id %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to icon('chevron-left'), votes_path, class: "btn btn-primary" %>

              <%= link_to icon('edit'), edit_vote_path(@vote), class: "btn btn-warning" %>

              <%= link_to icon('trash-o'), @vote, method: :delete, data: { confirm: "Do you really want to delete this vote?" }, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->